version: '3.8'

services:
  authservice:
    image: authservice:latest
    build:
      context: ./authservice
    ports:
      - "8081:8081"
    networks:
      - app-network

  backend:
    image: backendcust:latest
    build:
      context: ./backendcust
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    image: frontendapp:latest
    build:
      context: ./FRONT-END-APP
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend
      - authservice

networks:
  app-network:
    driver: bridge
